name: Run tests and build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '20'

    - name: Run tests
      run: ./mvnw test

    - name: Build
      run: |
        # Download and set up Maven
        mvn -N io.takari:maven:wrapper
        ./mvnw clean install


    # - name: Run Spring Boot App
      # run: java -jar target/spring-boot-mysql-async-0.0.1-SNAPSHOT.jar
